version: "3.9"
services:
  mariadb-user:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: biquesdam
      MARIADB_DATABASE: biquesdam
      MARIADB_USER: biquesdam
      MARIADB_PASSWORD: biquesdam
    ports:
      - "3306:3306"
