version: "3.9"
services:
  mariadb-user:
    image: mariadb
    container_name: db-users
    environment:
      MARIADB_ROOT_PASSWORD: biquesdam
      MARIADB_DATABASE: biquesdam
      MARIADB_USER: biquesdam
      MARIADB_PASSWORD: biquesdam
    ports:
      - "3306:3306"

  api-users:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: api-users
    ports:
      - "8383:8383"
    depends_on:
      - mariadb-user

