version: "3.9"
services:
  #USER
  mariadb-user:
    image: mariadb
    container_name: db-users
    environment:
      MARIADB_ROOT_PASSWORD: biquesdam
      MARIADB_DATABASE: biquesdam
      MARIADB_USER: biquesdam
      MARIADB_PASSWORD: biquesdam
  

  api-users:
    build:
      context: ../../Microservicio-Usuarios
      dockerfile: ./docker/Dockerfile
    container_name: api-users
    ports:
      - "8383:8383"
    depends_on:
      - mariadb-user

##PEDIDOS
  mongodb-pedidos:
    image: mongo
    container_name: mongodb-pedidos

  api-order:
    build:
      context: ../../Microservicio-Pedidos
      dockerfile: ./docker/Dockerfile
    container_name: api-order
    ports:
      - "8282:8282"
    depends_on:
      - mongodb-pedidos

##PRODUCTS
  api-products:
    build:
      context: ../../Microservicio-Producto-Servicios
      dockerfile: ./docker/Dockerfile
    container_name: api-products


  gateway:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: gateway
    ports:
      - "6969:6969"
    depends_on:
      - api-products
      - api-users
      - api-order







